# Generated by Django 6.0.4 on 2026-04-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter number with country code, e.g., +1234567890', max_length=20, null=True),
        ),
    ]
