# Generated by Django 6.0.4 on 2026-04-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_teammember_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='telegram_number',
            field=models.CharField(blank=True, help_text='Enter Telegram username or number (e.g. username or +1234567890)', max_length=50, null=True),
        ),
    ]
